
stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run lint
    - npm run build -- --prod

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test