stages:
  - install
  - build
  - test
  - toPDF
  - toPDF1

setup-job 1/2:
  stage: install
  tags: 
      - nodejs
      - npm 
  script: 
    - npm ci

setup-job 2/2:
  stage: build
  tags: 
      - nodejs
      - npm
  script: 
    - npm build

unittest-job:
  stage: test
  tags: 
     - nodejs
     - npm 
  script: 
     -  npm run test

job 1/2::

  stage: toPDF
  needs: []  
  tags:
     - nodejs
  script:
     - makepdf
  artifacts:
    expire_in: 1 week
    paths:
      - "todoList/todoList.pdf"
  when: on_success

job 2/2:
  stage: toPDF1
  script:
    - echo "PDF1"





