stages:
  - client

client:job:
  stage: client
  tags: 
      - nodejs
      - npm
  script: 
    - npm install
    - npm i eslint
    - npm init @eslint/config
    - node_modules/eslint/bin/eslint.js
  cache:
    key: node-cache
    paths:
      - node_modules

