stages:
  - install
  - build
  - test
  - lint
  - sonarqube
  - toPDF
  - toPDF1



setup-job 1/2:
  stage: install
  tags:
      - nodejs
      - npm
  script:
    - npm ci
  only:
    - merge_requests
    - master


setup-job 2/2:
  stage: build
  tags:
      - nodejs
      - npm
  script:
    - npm build
  only:
    - merge_requests
    - master


lint:
  stage: lint
  tags:
    - nodejs
  before_script:
    - cd frontend
    - npm install
  script:
    - npx eslint .
  #only:
    #- merge_requests
    #- master


test:
  stage: test
  tags:
    - nodejs
  before_script:
    - npm install
  script:
    - apt update
    - apt upgrade -y
    - apt install -y chromium
    - export CHROME_BIN=/usr/bin/chromium
    - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessCI
  #only:
    #- merge_requests
    #- master



# go to: https://scm.thm.de/sonar/dashboard?id=kms-todo-2023
sonarqube:
  stage:
    sonarqube
  tags:
    - sonarqube
  variables:
    GIT_DEPTH: "0"
  script:
    - sonar-scanner -D"sonar.projectKey=kms-todo-2023" -Dsonar.login=f7ed6a1b43851b7af315758cb25fe1318fcf1aa4 -Dsonar.host.url=https://scm.thm.de/sonar
  #only:
    #- master


#unittest-job:
#  stage: test
#  tags:
#    - nodejs
#    - npm
#  script:
#    - npm install
#    - ng test
#  only:
#    - merge_requests
#    - master


#job 1/2::
#stage: toPDF
#needs: []
#tags:
#  - nodejs
#script:
#  - makepdf
#artifacts:
#  expire_in: 1 week
#  paths:
#    - "todoList/todoList.pdf"
#when: on_success

#job 2/2:
#  stage: toPDF1
#  script:
#    - echo "PDF1"
