stages:
  - setup
   
setup:
  stage: client
  tags: 
      - nodejs
      - npm 
  script: 
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
    - source ~/.bashrc
    - nvm install v16.15.1
    - npm install
    - npm install @angular-eslint/schematics@13.3.0
    - npm run build 
    - npm i eslint
    - npm init @eslint/config
    - npm install @typescript-eslint/eslint-plugin@latest --save-dev
    - node_modules/eslint/bin/eslint.js
  cache:
    key: node-cache
    paths:
      - dist
      - node_modules
