stages:
  - install
  - build
  - test
  - toPDF
  - toPDF1

install-job:
  stage: install
  tags: 
      - nodejs
      - npm 
  script: 
    - npm ci

build-job:
  stage: build
  tags: 
      - nodejs
      - npm
  script: 
    - npm build

#unittest-job:
#  stage: test
#  tags: 
#      - nodejs
#      - npm 
#  script: 
#    -   npm run test


job 1/2::
  image:
    name: texlive/texlive
  stage: toPDF
  needs: []
  script:
    - echo "PDF"
  artifacts:
    expire_in: 1 week
    paths:
      - "todoList/todoList.pdf"
  when: on_success

job 2/2:
  stage: toPDF1
  script:
    - echo "PDF1"





